# Generated by Django 3.2 on 2024-10-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePaciente', models.CharField(max_length=50)),
                ('apellidoPaciente', models.CharField(max_length=50)),
                ('rutPaciente', models.IntegerField()),
                ('fechaNacimiento', models.DateField()),
                ('correoPaciente', models.EmailField(max_length=254)),
            ],
        ),
    ]
